좋아요 기능 구현완료 하였습니다.
KAPUIST/Today-I-Workout pull request #30
Opened 2024-06-03 10:26 UTC by Budubuu

2024-06-03 11:18 UTC, KAPUIST requested changes
PR 제목도 수정해 주시기바랍니다.

2024-06-03 11:18 UTC, KAPUIST commented on src/routers/post.router.js
> +import { liketoggle } from "../services/post.service.js";
함수명 카멜케이스 부탁드립니다.

2024-06-03 11:18 UTC, KAPUIST commented on src/routers/post.router.js
> +        return res
에러미들웨어를 사용해주세요.

2024-06-03 11:18 UTC, KAPUIST commented on src/services/post.service.js
> +            return { status: STATUS_CODES.NOT_FOUND, message: "포스트를 찾을 수 없습니다." };
에러핸들러를 사용해주세요.

2024-06-03 11:18 UTC, KAPUIST commented on src/services/post.service.js
> +            return { status: STATUS_CODES.BAD_REQUEST, message: "자신이 만든 포스트는 좋아요를 누를 수 없습니다." };
에러핸들러를 사용해주세요.

2024-06-03 11:18 UTC, KAPUIST commented on src/services/post.service.js
> +                post_id_user_id: {
오잉?! 이거되나용?

2024-06-03 11:18 UTC, KAPUIST commented on src/services/post.service.js
> +            return { status: STATUS_CODES.CREATED, message: "좋아요를 눌렀습니다." };
에러핸들러를 사용해주세요

2024-06-03 11:21 UTC, seungyeopyoo commented
좋아요 기능 좋아요

2024-06-03 11:27 UTC, Budubuu commented on src/routers/post.router.js
> +import { liketoggle } from "../services/post.service.js";
했습니다

2024-06-04 03:24 UTC, KAPUIST requested changes
두둥

2024-06-04 03:24 UTC, KAPUIST commented on src/routers/auth.router.js
> +        throw new ErrorHandler(STATUS_CODES.NO_CONTENT, "로그아웃 완료");
로그아웃완료인데 에러를 띄울 필요는 없어보입니다.

2024-06-04 04:52 UTC, Budubuu commented on src/services/post.service.js
> +                post_id_user_id: {
스키마에 복합 연산자 추가했습니다

2024-06-04 05:18 UTC, merged